CREATE TABLE Items (
    ITEM_ID VARCHAR(10) PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL,
    INVENTORY_STATUS INTEGER NOT NULL);

CREATE TABLE Items2 (
    ITEM_ID VARCHAR(10) PRIMARY KEY,
    DESCRIPTION VARCHAR(50)  NULL,
    INVENTORY_STATUS INTEGER  NULL);